# Generated by Django 3.2.2 on 2021-05-31 19:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('time', models.TimeField()),
                ('rent_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='cds.cd')),
            ],
        ),
        migrations.CreateModel(
            name='RentedCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(verbose_name=datetime.datetime)),
                ('date_to', models.DateTimeField(default=datetime.datetime(2021, 5, 31, 21, 0, 20, 387104))),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_cd_rents', to='cds.cd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cd',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cds', to='cds.genre'),
        ),
        migrations.AddField(
            model_name='cd',
            name='usercd_rentier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cds', to=settings.AUTH_USER_MODEL),
        ),
    ]
