# Generated by Django 3.2.2 on 2021-06-03 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0003_auto_20210531_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedcd',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 20, 9, 13, 612924)),
        ),
    ]
