# Generated by Django 3.2.2 on 2021-05-30 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldrental', '0003_auto_20210530_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedbook',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 22, 26, 29, 286185)),
        ),
        migrations.AlterField(
            model_name='rentedbook',
            name='date_from',
            field=models.DateTimeField(verbose_name=datetime.datetime),
        ),
    ]
