# Generated by Django 3.2.2 on 2021-05-31 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldrental', '0004_auto_20210530_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedbook',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 21, 0, 20, 383375)),
        ),
    ]
