# Generated by Django 3.2.2 on 2021-05-31 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldrental', '0006_alter_rentedbook_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedbook',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 21, 32, 59, 140481)),
        ),
    ]
