# Generated by Django 3.2.2 on 2021-06-03 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldrental', '0008_alter_rentedbook_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedbook',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 20, 15, 34, 352095)),
        ),
    ]
